"""NỘI DUNG bộ dữ liệu mẫu phân hệ Công việc (CR-218).

Chỉ có DỮ LIỆU, không có logic — phần dựng nằm ở `app/seed_cong_viec_demo.py`.

Vì sao tách: bộ này dài và sẽ còn được sửa nội dung nhiều (thêm dự án, đổi tên
việc), còn đoạn dựng thì gần như không đổi. Trộn chung một tệp là mỗi lần thêm
một dòng việc lại phải đọc qua cả trăm dòng vòng lặp.

Quy ước trong tệp này:

- `due`: SỐ NGÀY so với hôm nay lúc chạy seed — âm là quá hạn, `0` là hôm nay,
  `None` là chưa đặt hạn. Ghi lệch ngày như vậy để bộ dữ liệu luôn có sẵn cả ba
  sắc thái màu trên thẻ (đỏ / cam / thường) dù chạy vào ngày nào.
- `status`: `1` đang mở · `2` hoàn thành · `3` đã hủy (theo `WorkTaskStatus`).
- `role`: `1` chủ · `2` quản trị · `3` thành viên · `4` khách xem (`WorkMemberRole`).
- Người dùng MÃ NHÂN SỰ (`tab_employee.code`), không dùng id: id đổi theo môi
  trường, mã thì không.
"""

#  Nhóm (thư mục) — `parent` trỏ tên nhóm cha, tối đa 2 cấp (A-08).
GROUPS = [
    {"name": "Khối Vận hành", "parent": None,
     "desc": "Việc của các phòng vận hành: thu mua, kho, dự án nội bộ.",
     "members": [("DEGO0001", 1), ("DEMOQL", 2), ("DEMONV", 3)]},
    {"name": "Tổ Kho vận", "parent": "Khối Vận hành",
     "desc": "Nhóm con của Khối Vận hành — kiểm kê, luân chuyển, giao nhận.",
     "members": [("DEMOQL", 1), ("DEMO_PURCHASER", 3)]},
    {"name": "Khối Kinh doanh", "parent": None,
     "desc": "Kế hoạch bán hàng, marketing, chăm sóc khách hàng.",
     "members": [("DEMOTP", 1), ("TVB_KD1", 2), ("TVB_KD2", 3), ("TVB_KD3", 3)]},
]

#  Năm "dự án" = năm task list. Mỗi list có bộ cột, tag, trường nhãn riêng —
#  đúng mô hình "mỗi list là một bảng độc lập" của Lark.
LISTS = [
    {
        "name": "Dự án ERP v2",
        "group": "Khối Vận hành",
        "color": "violet",
        "desc": "Dựng phân hệ mới trên frontend-v2 và dời màn từ bản cũ.",
        "owner": "DEGO0001",
        "members": [("DEMONV", 2), ("TVB_NS1", 3), ("TVB_KT1", 3), ("DEMOTP2", 4)],
        "sections": [("Chờ phân tích", "slate"), ("Đang làm", "sky"),
                     ("Chờ kiểm thử", "amber"), ("Xong", "emerald")],
        "tags": [("Backend", "blue"), ("Giao diện", "violet"), ("Gấp", "red"),
                 ("Nợ kỹ thuật", "slate")],
        "label_field": {"name": "Phiên bản", "options": [("v2.0", "sky"), ("v2.1", "teal"),
                                                         ("Chưa xếp", "slate")]},
        "tasks": [
            {"title": "Dựng bảng dữ liệu phân hệ Công việc", "section": 3, "priority": 1,
             "due": -6, "status": 2, "pic": ["DEGO0001"], "followers": ["DEMONV"],
             "tags": ["Backend"], "label": "v2.0",
             "subtasks": [("Chốt 12 bảng tab_work_*", True), ("Sinh migration", True),
                          ("Chạy thử downgrade", True)]},
            {"title": "API lõi: nhóm, danh sách, thành viên", "section": 3, "priority": 1,
             "due": -3, "status": 2, "pic": ["DEGO0001", "DEMONV"], "followers": [],
             "tags": ["Backend"], "label": "v2.0",
             "subtasks": [("Hàm visible_list_ids", True), ("Kế thừa vai trò từ nhóm", True),
                          ("Test chặn người ngoài", True)]},
            {"title": "Kanban kéo thả + panel chi tiết", "section": 2, "priority": 1,
             "due": 0, "status": 1, "pic": ["DEMONV"], "followers": ["DEGO0001"],
             "tags": ["Giao diện", "Gấp"], "label": "v2.0",
             "subtasks": [("Thẻ việc và chip màu", True), ("Kéo thả giữa cột", True),
                          ("Panel trượt bên phải", True), ("Khối việc con", False),
                          ("Nhớ tùy chọn khung nhìn", False)]},
            {"title": "Bộ lọc điều kiện cho khung nhìn", "section": 0, "priority": 2,
             "due": 5, "status": 1, "pic": ["DEMONV"], "followers": [],
             "tags": ["Giao diện"], "label": "v2.1",
             "subtasks": [("Nối khung conditional-filter", False),
                          ("Trường lọc động theo nhãn của list", False)]},
            {"title": "Bình luận và chuông giao việc", "section": 0, "priority": 2,
             "due": 12, "status": 1, "pic": ["DEGO0001"], "followers": ["DEMOQL"],
             "tags": ["Backend"], "label": "v2.1",
             "subtasks": [("Đăng ký entity ở comment_registry", False),
                          ("Bắn chuông khi được giao việc", False),
                          ("Đưa vào tab Việc cần làm", False)]},
            {"title": "Rà lại phân quyền hai tầng trước khi lên dev", "section": 1,
             "priority": 2, "due": 3, "status": 1, "pic": ["TVB_NS1"], "followers": ["DEGO0001"],
             "tags": ["Backend", "Nợ kỹ thuật"], "label": "v2.0",
             "subtasks": [("Soát mọi query có lọc thành viên", False),
                          ("Thử bằng tài khoản ngoài danh sách", False)]},
            {"title": "Dọn cảnh báo ESLint tồn đọng", "section": 0, "priority": 4,
             "due": None, "status": 1, "pic": [], "followers": [],
             "tags": ["Nợ kỹ thuật"], "label": "Chưa xếp", "subtasks": []},
            {"title": "Viết hướng dẫn sử dụng cho người dùng cuối", "section": 0,
             "priority": 3, "due": 20, "status": 1, "pic": ["TVB_NS2"], "followers": [],
             "tags": [], "label": None,
             "subtasks": [("Chụp màn hình từng bước", False), ("Đưa lên Help Center", False)]},
            {"title": "Thử nghiệm Gantt bằng thư viện ngoài", "section": 0, "priority": 4,
             "due": None, "status": 3, "pic": ["DEMONV"], "followers": [],
             "tags": [], "label": "Chưa xếp", "subtasks": []},
            {"title": "Khảo sát nhu cầu báo cáo của ban lãnh đạo", "section": 1,
             "priority": 3, "due": -1, "status": 1, "pic": ["DEMOQL"], "followers": ["DEMOTP"],
             "tags": [], "label": "v2.1",
             "subtasks": [("Phỏng vấn 3 trưởng phòng", True), ("Tổng hợp thành bản đề xuất", False)]},
        ],
    },
    {
        "name": "Thu mua Quý 3/2026",
        "group": "Khối Vận hành",
        "color": "sky",
        "desc": "Theo dõi các gói mua sắm lớn trong quý và tiến độ nhà cung cấp.",
        "owner": "DEMOQL",
        "members": [("DEMO_PURCHASER", 2), ("DEMONV", 3), ("TVB_KT1", 3),
                    ("DEMO_MANAGER_PURCHASE", 2), ("TVB_KT2", 4)],
        "sections": [("Cần làm", "slate"), ("Đang khảo sát", "sky"),
                     ("Chờ duyệt", "amber"), ("Hoàn thành", "emerald")],
        "tags": [("Bao bì", "orange"), ("Nguyên liệu", "lime"), ("Vận chuyển", "teal"),
                 ("Gấp", "red")],
        "label_field": {"name": "Mức chi", "options": [("Dưới 50tr", "slate"),
                                                       ("50–200tr", "amber"),
                                                       ("Trên 200tr", "red")]},
        "tasks": [
            {"title": "Khảo sát giá thùng carton 3 lớp", "section": 3, "priority": 2,
             "due": -10, "status": 2, "pic": ["DEMO_PURCHASER"], "followers": ["DEMOQL"],
             "tags": ["Bao bì"], "label": "50–200tr",
             "subtasks": [("Xin báo giá 3 NCC", True), ("So sánh đơn giá theo sản lượng", True),
                          ("Trình duyệt phương án", True)]},
            {"title": "Chốt nhà cung cấp nhãn dán sản phẩm", "section": 2, "priority": 1,
             "due": -2, "status": 1, "pic": ["DEMO_PURCHASER", "DEMONV"], "followers": ["DEMOQL"],
             "tags": ["Bao bì", "Gấp"], "label": "50–200tr",
             "subtasks": [("Đối chiếu mẫu in thử", True), ("Thương lượng công nợ 30 ngày", False),
                          ("Ký hợp đồng nguyên tắc", False)]},
            {"title": "Đàm phán lại cước vận chuyển tuyến miền Tây", "section": 1,
             "priority": 2, "due": 4, "status": 1, "pic": ["DEMONV"], "followers": [],
             "tags": ["Vận chuyển"], "label": "Trên 200tr",
             "subtasks": [("Thu thập cước 3 tháng gần nhất", True),
                          ("Gửi yêu cầu chào lại giá", False)]},
            {"title": "Bổ sung nhà cung cấp dự phòng cho nguyên liệu chính", "section": 1,
             "priority": 2, "due": 9, "status": 1, "pic": ["DEMO_MANAGER_PURCHASE"],
             "followers": ["DEMOQL"], "tags": ["Nguyên liệu"], "label": "Trên 200tr",
             "subtasks": [("Lập danh sách ứng viên", True), ("Đánh giá năng lực sản xuất", False),
                          ("Chạy thử đơn hàng nhỏ", False)]},
            {"title": "Kiểm tra hồ sơ pháp lý nhà cung cấp mới", "section": 0, "priority": 3,
             "due": 6, "status": 1, "pic": ["TVB_KT1"], "followers": [],
             "tags": [], "label": "Dưới 50tr",
             "subtasks": [("Giấy phép kinh doanh", False), ("Chứng nhận chất lượng", False)]},
            {"title": "Rà soát công nợ quá hạn với nhà cung cấp", "section": 2, "priority": 1,
             "due": 0, "status": 1, "pic": ["TVB_KT1", "TVB_KT2"], "followers": ["DEMOQL"],
             "tags": ["Gấp"], "label": "Trên 200tr",
             "subtasks": [("Xuất bảng tuổi nợ", True), ("Lên kế hoạch thanh toán tuần", False)]},
            {"title": "Cập nhật đơn giá danh mục vật tư lên hệ thống", "section": 0,
             "priority": 3, "due": 14, "status": 1, "pic": ["DEMO_PURCHASER"], "followers": [],
             "tags": ["Nguyên liệu"], "label": "Dưới 50tr", "subtasks": []},
            {"title": "Hủy gói mua máy dán nhãn (đổi phương án thuê)", "section": 0,
             "priority": 4, "due": None, "status": 3, "pic": ["DEMOQL"], "followers": [],
             "tags": [], "label": None, "subtasks": []},
            {"title": "Tổng kết tiết kiệm chi phí quý 2", "section": 3, "priority": 3,
             "due": -20, "status": 2, "pic": ["DEMOQL"], "followers": ["DEMOTP"],
             "tags": [], "label": "Dưới 50tr",
             "subtasks": [("Lấy số liệu từ báo cáo mua hàng", True), ("Soạn slide trình bày", True)]},
            {"title": "Đánh giá nhà cung cấp định kỳ 6 tháng", "section": 1, "priority": 2,
             "due": 21, "status": 1, "pic": ["DEMO_MANAGER_PURCHASE"], "followers": ["DEMO_PURCHASER"],
             "tags": ["Nguyên liệu", "Bao bì"], "label": "50–200tr",
             "subtasks": [("Gửi phiếu chấm điểm cho các phòng", False),
                          ("Tổng hợp điểm và xếp hạng", False),
                          ("Thông báo kết quả cho NCC", False)]},
        ],
    },
    {
        "name": "Kiểm kê kho cuối quý",
        "group": "Tổ Kho vận",
        "color": "amber",
        "desc": "Kế hoạch kiểm kê toàn bộ kho và xử lý chênh lệch.",
        "owner": "DEMOQL",
        "members": [("DEMO_PURCHASER", 3), ("DEMONV", 3), ("TVB_KT3", 4)],
        "sections": [("Chuẩn bị", "slate"), ("Đang kiểm", "sky"), ("Đã xong", "emerald")],
        "tags": [("Kho Bắc", "blue"), ("Kho Nam", "orange"), ("Chênh lệch", "red")],
        "label_field": {"name": "Ca kiểm", "options": [("Ca sáng", "amber"), ("Ca chiều", "violet")]},
        "tasks": [
            {"title": "Lập kế hoạch và phân công tổ kiểm kê", "section": 2, "priority": 2,
             "due": -8, "status": 2, "pic": ["DEMOQL"], "followers": [],
             "tags": [], "label": "Ca sáng",
             "subtasks": [("Chia tổ theo khu vực", True), ("In phiếu kiểm kê", True)]},
            {"title": "Kiểm kê kho nguyên liệu miền Bắc", "section": 1, "priority": 1,
             "due": 1, "status": 1, "pic": ["DEMO_PURCHASER"], "followers": ["DEMOQL"],
             "tags": ["Kho Bắc"], "label": "Ca sáng",
             "subtasks": [("Đếm thực tế kệ A1–A9", True), ("Đếm thực tế kệ B1–B6", False),
                          ("Đối chiếu với tồn hệ thống", False)]},
            {"title": "Kiểm kê kho bao bì miền Nam", "section": 1, "priority": 1,
             "due": 2, "status": 1, "pic": ["DEMONV"], "followers": ["DEMOQL"],
             "tags": ["Kho Nam"], "label": "Ca chiều",
             "subtasks": [("Đếm thực tế khu C", False), ("Chụp ảnh hàng hư hỏng", False)]},
            {"title": "Xử lý chênh lệch tồn kho đợt trước", "section": 0, "priority": 2,
             "due": -4, "status": 1, "pic": ["DEMOQL"], "followers": ["TVB_KT3"],
             "tags": ["Chênh lệch"], "label": None,
             "subtasks": [("Truy nguyên phiếu xuất thiếu", True), ("Lập biên bản điều chỉnh", False)]},
            {"title": "Dán lại nhãn vị trí kệ hàng", "section": 0, "priority": 4,
             "due": None, "status": 1, "pic": [], "followers": [], "tags": [], "label": None,
             "subtasks": []},
            {"title": "Báo cáo kiểm kê gửi ban giám đốc", "section": 0, "priority": 2,
             "due": 7, "status": 1, "pic": ["DEMOQL"], "followers": ["DEMOTP"],
             "tags": [], "label": "Ca chiều",
             "subtasks": [("Tổng hợp số liệu hai kho", False), ("Ghi chú nguyên nhân chênh lệch", False)]},
        ],
    },
    {
        "name": "Ra mắt sản phẩm Dr Xanh",
        "group": "Khối Kinh doanh",
        "color": "emerald",
        "desc": "Chiến dịch giới thiệu dòng sản phẩm mới ra thị trường.",
        "owner": "DEMOTP",
        #  DEGO0001 (tài khoản admin hay dùng để xem thử) vào đây với vai QUẢN TRỊ,
        #  còn ở list "Tuyển dụng" bên dưới chỉ là KHÁCH XEM — để mở hai list cạnh
        #  nhau là thấy ngay khác biệt: bên này sửa được, bên kia mọi nút đều tắt.
        "members": [("DEGO0001", 2), ("TVB_KD1", 2), ("TVB_KD2", 3), ("TVB_KD3", 3),
                    ("DEMOQL", 4)],
        "sections": [("Ý tưởng", "slate"), ("Đang triển khai", "sky"),
                     ("Chờ duyệt nội dung", "amber"), ("Đã chạy", "emerald")],
        "tags": [("Nội dung", "violet"), ("Sự kiện", "fuchsia"), ("Quảng cáo", "sky"),
                 ("Ngân sách", "amber")],
        "label_field": {"name": "Kênh", "options": [("Facebook", "blue"), ("Sàn TMĐT", "orange"),
                                                    ("Cửa hàng", "emerald"), ("Chưa chọn", "slate")]},
        "tasks": [
            {"title": "Chốt thông điệp và bộ nhận diện chiến dịch", "section": 3, "priority": 1,
             "due": -12, "status": 2, "pic": ["TVB_KD1"], "followers": ["DEMOTP"],
             "tags": ["Nội dung"], "label": "Chưa chọn",
             "subtasks": [("Duyệt 3 phương án thông điệp", True), ("Chốt bảng màu và logo", True)]},
            {"title": "Sản xuất video giới thiệu 60 giây", "section": 2, "priority": 1,
             "due": 0, "status": 1, "pic": ["TVB_KD2"], "followers": ["TVB_KD1"],
             "tags": ["Nội dung", "Quảng cáo"], "label": "Facebook",
             "subtasks": [("Viết kịch bản", True), ("Quay tại xưởng", True),
                          ("Dựng và chỉnh màu", False), ("Duyệt bản cuối", False)]},
            {"title": "Lên kế hoạch ngân sách quảng cáo tháng 9", "section": 1, "priority": 2,
             "due": 3, "status": 1, "pic": ["TVB_KD1"], "followers": ["DEMOTP", "TVB_KT1"],
             "tags": ["Ngân sách"], "label": "Sàn TMĐT",
             "subtasks": [("Phân bổ theo kênh", True), ("Trình duyệt ngân sách", False)]},
            {"title": "Chuẩn bị gian hàng sự kiện ra mắt", "section": 1, "priority": 2,
             "due": 8, "status": 1, "pic": ["TVB_KD3"], "followers": ["TVB_KD1"],
             "tags": ["Sự kiện"], "label": "Cửa hàng",
             "subtasks": [("Thuê mặt bằng", True), ("Đặt in standee và backdrop", False),
                          ("Chuẩn bị hàng mẫu", False)]},
            {"title": "Đăng bài giới thiệu trên fanpage", "section": 0, "priority": 3,
             "due": 10, "status": 1, "pic": ["TVB_KD2"], "followers": [],
             "tags": ["Nội dung"], "label": "Facebook",
             "subtasks": [("Soạn 5 bài viết", False), ("Lên lịch đăng", False)]},
            {"title": "Đào tạo đội bán hàng về sản phẩm mới", "section": 0, "priority": 2,
             "due": 5, "status": 1, "pic": ["DEMOTP"], "followers": ["TVB_KD3"],
             "tags": [], "label": "Cửa hàng",
             "subtasks": [("Soạn tài liệu bán hàng", False), ("Tổ chức buổi đào tạo", False)]},
            {"title": "Khảo sát phản hồi khách hàng sau 2 tuần", "section": 0, "priority": 3,
             "due": 25, "status": 1, "pic": [], "followers": ["DEMOTP"],
             "tags": [], "label": "Chưa chọn", "subtasks": []},
            {"title": "Chạy thử quảng cáo trên sàn TMĐT", "section": 2, "priority": 2,
             "due": -1, "status": 1, "pic": ["TVB_KD2", "TVB_KD3"], "followers": [],
             "tags": ["Quảng cáo"], "label": "Sàn TMĐT",
             "subtasks": [("Tạo tài khoản quảng cáo", True), ("Chạy thử 3 ngày ngân sách nhỏ", False),
                          ("Đánh giá tỉ lệ chuyển đổi", False)]},
            {"title": "Bỏ phương án tặng quà kèm đơn hàng", "section": 0, "priority": 4,
             "due": None, "status": 3, "pic": ["TVB_KD1"], "followers": [],
             "tags": ["Ngân sách"], "label": None, "subtasks": []},
        ],
    },
    {
        "name": "Tuyển dụng & Đào tạo Q3",
        "group": None,   # list đứng lẻ ngoài nhóm — vẫn hợp lệ (A-08)
        "color": "rose",
        "desc": "Danh sách đứng ngoài mọi nhóm, để thử nhánh list lẻ trên sidebar.",
        "owner": "TVB_NS1",
        "members": [("TVB_NS2", 2), ("TVB_NS3", 3), ("DEMOTP", 4), ("DEGO0001", 4)],
        "sections": [("Cần làm", "slate"), ("Đang xử lý", "sky"), ("Hoàn thành", "emerald")],
        "tags": [("Tuyển dụng", "blue"), ("Đào tạo", "teal"), ("Nội bộ", "slate")],
        "label_field": {"name": "Vị trí", "options": [("Kho vận", "amber"), ("Kinh doanh", "emerald"),
                                                      ("Văn phòng", "sky")]},
        "tasks": [
            {"title": "Đăng tin tuyển 2 nhân viên kho", "section": 1, "priority": 2,
             "due": 2, "status": 1, "pic": ["TVB_NS2"], "followers": ["TVB_NS1"],
             "tags": ["Tuyển dụng"], "label": "Kho vận",
             "subtasks": [("Soạn mô tả công việc", True), ("Đăng lên 3 kênh tuyển dụng", True),
                          ("Sàng lọc hồ sơ", False)]},
            {"title": "Phỏng vấn ứng viên nhân viên kinh doanh", "section": 1, "priority": 1,
             "due": 0, "status": 1, "pic": ["TVB_NS1", "DEMOTP"], "followers": [],
             "tags": ["Tuyển dụng"], "label": "Kinh doanh",
             "subtasks": [("Hẹn lịch 5 ứng viên", True), ("Chấm điểm theo khung năng lực", False)]},
            {"title": "Tổ chức đào tạo an toàn lao động", "section": 0, "priority": 2,
             "due": 11, "status": 1, "pic": ["TVB_NS3"], "followers": ["TVB_NS1"],
             "tags": ["Đào tạo"], "label": "Kho vận",
             "subtasks": [("Mời đơn vị đào tạo", False), ("Chốt danh sách tham dự", False)]},
            {"title": "Hoàn tất hồ sơ nhân sự mới vào tháng 8", "section": 2, "priority": 3,
             "due": -5, "status": 2, "pic": ["TVB_NS2"], "followers": [],
             "tags": ["Nội bộ"], "label": "Văn phòng",
             "subtasks": [("Ký hợp đồng thử việc", True), ("Khai báo bảo hiểm", True)]},
            {"title": "Rà soát mô tả công việc toàn phòng", "section": 0, "priority": 4,
             "due": None, "status": 1, "pic": [], "followers": [], "tags": ["Nội bộ"],
             "label": None, "subtasks": []},
            {"title": "Chuẩn bị đánh giá thử việc quý", "section": 0, "priority": 3,
             "due": 16, "status": 1, "pic": ["TVB_NS3"], "followers": ["TVB_NS1"],
             "tags": ["Nội bộ"], "label": "Văn phòng",
             "subtasks": [("Gửi biểu mẫu cho quản lý", False), ("Tổng hợp kết quả", False)]},
        ],
    },
]
