import { DOSSIER_STATUS, type Dossier } from '../types/dossier'

/**
 * DỮ LIỆU MẪU — sống hoàn toàn trong trình duyệt, không có API nào phía sau.
 *
 * Mục đích: chốt hình hài màn danh sách trước khi dựng backend. Đủ 26 dòng để
 * phân trang, ô lọc và ô tìm kiếm có việc để làm; cố ý pha đủ năm trạng thái,
 * vài hồ sơ **vô thời hạn** (`expiry_date` rỗng) và vài hồ sơ chưa đính kèm tệp
 * nào — ba ca dễ vẽ hỏng nhất.
 *
 * Xóa tệp này ngay khi `dossier-api.ts` gọi được API thật.
 */
export const MOCK_DOSSIERS: Dossier[] = [
  {
    id: 1,
    code: 'HS-2026-001',
    name: 'Giấy chứng nhận đăng ký doanh nghiệp DEGO Holding',
    type_name: 'Pháp lý doanh nghiệp',
    department_name: 'Hành chính',
    owner_name: 'Nguyễn Thị Lan',
    issued_date: '2023-04-12',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 3,
    storage_location: 'Tủ A1 · P. Hành chính',
  },
  {
    id: 2,
    code: 'HS-2026-002',
    name: 'Hợp đồng thuê văn phòng trụ sở chính',
    type_name: 'Hợp đồng',
    department_name: 'Hành chính',
    owner_name: 'Nguyễn Thị Lan',
    issued_date: '2024-01-02',
    expiry_date: '2026-12-31',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 5,
    storage_location: 'Tủ A1 · P. Hành chính',
  },
  {
    id: 3,
    code: 'HS-2026-003',
    name: 'Giấy phép phòng cháy chữa cháy kho Bình Dương',
    type_name: 'Giấy phép',
    department_name: 'Kho vận',
    owner_name: 'Trần Văn Hùng',
    issued_date: '2023-09-18',
    expiry_date: '2026-09-30',
    status: DOSSIER_STATUS.EXPIRING,
    attachment_count: 2,
    storage_location: 'Tủ B3 · Kho Bình Dương',
  },
  {
    id: 4,
    code: 'HS-2026-004',
    name: 'Hồ sơ năng lực nhà cung cấp Thép Hòa Phát',
    type_name: 'Hồ sơ đối tác',
    department_name: 'Thu mua',
    owner_name: 'Lê Minh Quân',
    issued_date: '2025-03-05',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 8,
    storage_location: 'Tủ C2 · P. Thu mua',
  },
  {
    id: 5,
    code: 'HS-2026-005',
    name: 'Hợp đồng nguyên tắc cung cấp vật tư xây dựng 2026',
    type_name: 'Hợp đồng',
    department_name: 'Thu mua',
    owner_name: 'Lê Minh Quân',
    issued_date: '2026-01-15',
    expiry_date: '2026-12-31',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 4,
    storage_location: 'Tủ C2 · P. Thu mua',
  },
  {
    id: 6,
    code: 'HS-2026-006',
    name: 'Chứng nhận ISO 9001:2015',
    type_name: 'Chứng nhận',
    department_name: 'Sản xuất',
    owner_name: 'Phạm Thu Hà',
    issued_date: '2024-06-20',
    expiry_date: '2027-06-19',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 1,
    storage_location: 'Tủ D1 · Nhà máy',
  },
  {
    id: 7,
    code: 'HS-2026-007',
    name: 'Giấy phép môi trường nhà máy bê tông',
    type_name: 'Giấy phép',
    department_name: 'Sản xuất',
    owner_name: 'Phạm Thu Hà',
    issued_date: '2021-08-01',
    expiry_date: '2026-07-31',
    status: DOSSIER_STATUS.EXPIRED,
    attachment_count: 3,
    storage_location: 'Tủ D1 · Nhà máy',
  },
  {
    id: 8,
    code: 'HS-2026-008',
    name: 'Hồ sơ bảo hiểm cháy nổ bắt buộc 2026',
    type_name: 'Bảo hiểm',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2026-01-05',
    expiry_date: '2027-01-04',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 2,
    storage_location: 'Tủ E1 · P. Tài chính',
  },
  {
    id: 9,
    code: 'HS-2026-009',
    name: 'Hồ sơ vay vốn lưu động ngân hàng BIDV',
    type_name: 'Tài chính — Tín dụng',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2025-11-11',
    expiry_date: '2026-11-10',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 12,
    storage_location: 'Két tài liệu · P. Tài chính',
  },
  {
    id: 10,
    code: 'HS-2026-010',
    name: 'Quyết định bổ nhiệm Trưởng phòng Thu mua',
    type_name: 'Nhân sự',
    department_name: 'Nhân sự',
    owner_name: 'Vũ Hải Yến',
    issued_date: '2025-07-01',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 1,
    storage_location: 'Tủ F2 · P. Nhân sự',
  },
  {
    id: 11,
    code: 'HS-2026-011',
    name: 'Hồ sơ đăng ký nhãn hiệu DEGO',
    type_name: 'Sở hữu trí tuệ',
    department_name: 'Marketing',
    owner_name: 'Bùi Anh Tuấn',
    issued_date: '2024-10-09',
    expiry_date: '2034-10-08',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 6,
    storage_location: 'Tủ A3 · P. Hành chính',
  },
  {
    id: 12,
    code: 'HS-2026-012',
    name: 'Hồ sơ dự thầu gói cung cấp bê tông tươi KCN Sóng Thần',
    type_name: 'Hồ sơ thầu',
    department_name: 'Kinh doanh',
    owner_name: 'Ngô Quang Vinh',
    issued_date: '2026-02-20',
    expiry_date: '2026-05-20',
    status: DOSSIER_STATUS.EXPIRED,
    attachment_count: 15,
    storage_location: 'Tủ G1 · P. Kinh doanh',
  },
  {
    id: 13,
    code: 'HS-2026-013',
    name: 'Hồ sơ nghiệm thu công trình Vinhomes Grand Park — đợt 3',
    type_name: 'Nghiệm thu',
    department_name: 'Kinh doanh',
    owner_name: 'Ngô Quang Vinh',
    issued_date: '2026-06-30',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 9,
    storage_location: 'Tủ G2 · P. Kinh doanh',
  },
  {
    id: 14,
    code: 'HS-2026-014',
    name: 'Giấy phép vận chuyển hàng siêu trường siêu trọng',
    type_name: 'Giấy phép',
    department_name: 'Kho vận',
    owner_name: 'Trần Văn Hùng',
    issued_date: '2026-03-01',
    expiry_date: '2026-10-15',
    status: DOSSIER_STATUS.EXPIRING,
    attachment_count: 0,
    storage_location: 'Tủ B1 · P. Kho vận',
  },
  {
    id: 15,
    code: 'HS-2026-015',
    name: 'Hồ sơ đăng kiểm đội xe tải 2026',
    type_name: 'Phương tiện',
    department_name: 'Kho vận',
    owner_name: 'Trần Văn Hùng',
    issued_date: '2026-04-18',
    expiry_date: '2027-04-17',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 7,
    storage_location: 'Tủ B1 · P. Kho vận',
  },
  {
    id: 16,
    code: 'HS-2026-016',
    name: 'Hợp đồng dịch vụ kiểm toán năm tài chính 2025',
    type_name: 'Hợp đồng',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2025-12-01',
    expiry_date: '2026-06-30',
    status: DOSSIER_STATUS.ARCHIVED,
    attachment_count: 3,
    storage_location: 'Kho lưu trữ tầng hầm',
  },
  {
    id: 17,
    code: 'HS-2026-017',
    name: 'Hồ sơ quyết toán thuế TNDN 2024',
    type_name: 'Thuế',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2025-03-28',
    expiry_date: '',
    status: DOSSIER_STATUS.ARCHIVED,
    attachment_count: 21,
    storage_location: 'Kho lưu trữ tầng hầm',
  },
  {
    id: 18,
    code: 'HS-2026-018',
    name: 'Hồ sơ năng lực nhà cung cấp Xi măng Hà Tiên',
    type_name: 'Hồ sơ đối tác',
    department_name: 'Thu mua',
    owner_name: 'Lê Minh Quân',
    issued_date: '2026-05-06',
    expiry_date: '',
    status: DOSSIER_STATUS.DRAFT,
    attachment_count: 0,
    storage_location: '',
  },
  {
    id: 19,
    code: 'HS-2026-019',
    name: 'Phụ lục điều chỉnh giá hợp đồng cung cấp cát xây dựng',
    type_name: 'Hợp đồng',
    department_name: 'Thu mua',
    owner_name: 'Hoàng Thị Nga',
    issued_date: '2026-08-12',
    expiry_date: '2026-12-31',
    status: DOSSIER_STATUS.DRAFT,
    attachment_count: 1,
    storage_location: '',
  },
  {
    id: 20,
    code: 'HS-2026-020',
    name: 'Hồ sơ an toàn lao động công trường Thủ Đức',
    type_name: 'An toàn lao động',
    department_name: 'Sản xuất',
    owner_name: 'Phạm Thu Hà',
    issued_date: '2026-02-14',
    expiry_date: '2026-09-25',
    status: DOSSIER_STATUS.EXPIRING,
    attachment_count: 4,
    storage_location: 'Tủ D2 · Nhà máy',
  },
  {
    id: 21,
    code: 'HS-2026-021',
    name: 'Chứng chỉ hợp quy sản phẩm gạch không nung',
    type_name: 'Chứng nhận',
    department_name: 'Sản xuất',
    owner_name: 'Phạm Thu Hà',
    issued_date: '2024-11-22',
    expiry_date: '2027-11-21',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 2,
    storage_location: 'Tủ D1 · Nhà máy',
  },
  {
    id: 22,
    code: 'HS-2026-022',
    name: 'Hồ sơ đăng ký sử dụng hóa đơn điện tử',
    type_name: 'Thuế',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2022-05-30',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 2,
    storage_location: 'Tủ E1 · P. Tài chính',
  },
  {
    id: 23,
    code: 'HS-2026-023',
    name: 'Thỏa thuận bảo mật thông tin với đối tác phần mềm',
    type_name: 'Hợp đồng',
    department_name: 'Công nghệ thông tin',
    owner_name: 'Trịnh Đức Thắng',
    issued_date: '2026-07-07',
    expiry_date: '2029-07-06',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 1,
    storage_location: 'Tủ H1 · P. CNTT',
  },
  {
    id: 24,
    code: 'HS-2026-024',
    name: 'Hồ sơ nghiệm thu hệ thống ERP nội bộ giai đoạn 1',
    type_name: 'Nghiệm thu',
    department_name: 'Công nghệ thông tin',
    owner_name: 'Trịnh Đức Thắng',
    issued_date: '2026-09-01',
    expiry_date: '',
    status: DOSSIER_STATUS.DRAFT,
    attachment_count: 0,
    storage_location: '',
  },
  {
    id: 25,
    code: 'HS-2026-025',
    name: 'Hợp đồng lao động mẫu áp dụng từ 2026',
    type_name: 'Nhân sự',
    department_name: 'Nhân sự',
    owner_name: 'Vũ Hải Yến',
    issued_date: '2025-12-20',
    expiry_date: '',
    status: DOSSIER_STATUS.ACTIVE,
    attachment_count: 2,
    storage_location: 'Tủ F1 · P. Nhân sự',
  },
  {
    id: 26,
    code: 'HS-2026-026',
    name: 'Hồ sơ thanh lý tài sản cố định đợt 1/2026',
    type_name: 'Tài sản',
    department_name: 'Tài chính',
    owner_name: 'Đỗ Ngọc Mai',
    issued_date: '2026-04-09',
    expiry_date: '',
    status: DOSSIER_STATUS.ARCHIVED,
    attachment_count: 5,
    storage_location: 'Kho lưu trữ tầng hầm',
  },
]
