"""add_vehicle_and_seal_models

Revision ID: 020dab131963
Revises: 225c3966c99c
Create Date: 2026-08-19 04:44:40.864532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '020dab131963'
down_revision: Union[str, None] = '225c3966c99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_driver',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('external_company', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_seal_type',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tab_vehicle',
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('external_company', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('tab_seal_request',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('seal_type_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('first_approver_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_seal_created_by', 'tab_seal_request', ['created_by'], unique=False)
    op.create_index(op.f('ix_tab_seal_request_company_id'), 'tab_seal_request', ['company_id'], unique=False)
    op.create_index(op.f('ix_tab_seal_request_requester_id'), 'tab_seal_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tab_seal_request_seal_type_id'), 'tab_seal_request', ['seal_type_id'], unique=False)
    op.create_table('tab_vehicle_booking',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('end_location', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('attendees', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('first_approver_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('assigned_vehicle_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_driver_id', sa.BigInteger(), nullable=True),
    sa.Column('dispatched_by', sa.BigInteger(), nullable=True),
    sa.Column('dispatched_at', sa.String(length=20), nullable=False),
    sa.Column('driver_status', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tab_vehicle_booking_company_id'), 'tab_vehicle_booking', ['company_id'], unique=False)
    op.create_index(op.f('ix_tab_vehicle_booking_requester_id'), 'tab_vehicle_booking', ['requester_id'], unique=False)
    op.create_index('ix_vbooking_created_by', 'tab_vehicle_booking', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vbooking_created_by', table_name='tab_vehicle_booking')
    op.drop_index(op.f('ix_tab_vehicle_booking_requester_id'), table_name='tab_vehicle_booking')
    op.drop_index(op.f('ix_tab_vehicle_booking_company_id'), table_name='tab_vehicle_booking')
    op.drop_table('tab_vehicle_booking')
    op.drop_index(op.f('ix_tab_seal_request_seal_type_id'), table_name='tab_seal_request')
    op.drop_index(op.f('ix_tab_seal_request_requester_id'), table_name='tab_seal_request')
    op.drop_index(op.f('ix_tab_seal_request_company_id'), table_name='tab_seal_request')
    op.drop_index('ix_seal_created_by', table_name='tab_seal_request')
    op.drop_table('tab_seal_request')
    op.drop_table('tab_vehicle')
    op.drop_table('tab_seal_type')
    op.drop_table('tab_driver')
    # ### end Alembic commands ###
