"""company legal rep + employee/role fields

Revision ID: 0637020f405f
Revises: dafd7880380c
Create Date: 2026-07-01 04:57:02.442731
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0637020f405f'
down_revision: Union[str, None] = 'dafd7880380c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_company', sa.Column('legal_representative_id', sa.BigInteger(), nullable=True))
    op.add_column('tab_company', sa.Column('legal_rep_title', sa.String(length=100), nullable=False))
    op.add_column('tab_role', sa.Column('description', sa.String(length=255), nullable=False))
    op.alter_column('tab_role', 'code',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tab_role', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_role', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tab_role', 'code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_column('tab_role', 'description')
    op.drop_column('tab_company', 'legal_rep_title')
    op.drop_column('tab_company', 'legal_representative_id')
    # ### end Alembic commands ###
