"""bo may phe duyet dung chung

Nền của phase 3 — bảy bảng, KHÔNG đổi và KHÔNG xóa cột nào đang có. Bộ máy mới
đứng CẠNH mã duyệt cũ; `tab_approval_switch` mặc định TẮT nên chạy migration
này không đổi hành vi của bất kỳ luồng duyệt nào đang chạy.

⚠️ Đã bỏ tay phần `alter_column` trên `tab_comment_*` / `tab_ticket*` mà
autogenerate kéo vào — độ lệch có sẵn, không liên quan tới bảy bảng này.

Revision ID: 092b4e436d25
Revises: 874c6c3669b1
Create Date: 2026-08-17 07:55:24.843466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '092b4e436d25'
down_revision: Union[str, None] = '874c6c3669b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_approval_action',
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('node_seq', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.SmallInteger(), nullable=False),
    sa.Column('actor_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('on_behalf_of_id', sa.BigInteger(), nullable=True),
    sa.Column('delegation_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_action_instance', 'tab_approval_action', ['instance_id', 'id'], unique=False)
    op.create_table('tab_approval_flow',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'code', 'version_no', name='uq_approval_flow_code_version')
    )
    op.create_index(op.f('ix_tab_approval_flow_entity'), 'tab_approval_flow', ['entity'], unique=False)
    op.create_table('tab_approval_instance',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('entity_title', sa.String(length=500), nullable=False),
    sa.Column('flow_id', sa.BigInteger(), nullable=False),
    sa.Column('flow_version', sa.Integer(), nullable=False),
    sa.Column('flow_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('current_seq', sa.Integer(), nullable=False),
    sa.Column('started_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('finish_reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_instance_entity', 'tab_approval_instance', ['entity', 'entity_id', 'status'], unique=False)
    op.create_index(op.f('ix_tab_approval_instance_flow_id'), 'tab_approval_instance', ['flow_id'], unique=False)
    op.create_table('tab_approval_node',
    sa.Column('flow_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('branch_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('node_kind', sa.SmallInteger(), nullable=False),
    sa.Column('flow_role', sa.SmallInteger(), nullable=False),
    sa.Column('approver_kind', sa.SmallInteger(), nullable=False),
    sa.Column('approver_ref', sa.String(length=300), nullable=False),
    sa.Column('multi_mode', sa.SmallInteger(), nullable=False),
    sa.Column('quorum_percent', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('is_default_branch', sa.Boolean(), nullable=False),
    sa.Column('skip_duplicate', sa.SmallInteger(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('fallback_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('on_no_approver', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'seq', 'branch_key', name='uq_approval_node_seq')
    )
    op.create_index(op.f('ix_tab_approval_node_flow_id'), 'tab_approval_node', ['flow_id'], unique=False)
    op.create_table('tab_approval_switch',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', name='uq_approval_switch_entity')
    )
    op.create_table('tab_approval_task',
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('node_seq', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('assignee_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('reminded_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_task_assignee', 'tab_approval_task', ['assignee_employee_id', 'status'], unique=False)
    op.create_index('ix_approval_task_instance', 'tab_approval_task', ['instance_id', 'node_seq'], unique=False)
    op.create_table('tab_delegation',
    sa.Column('from_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('to_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delegation_from', 'tab_delegation', ['from_employee_id', 'is_active'], unique=False)
    op.create_index('ix_delegation_to', 'tab_delegation', ['to_employee_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delegation_to', table_name='tab_delegation')
    op.drop_index('ix_delegation_from', table_name='tab_delegation')
    op.drop_table('tab_delegation')
    op.drop_index('ix_approval_task_instance', table_name='tab_approval_task')
    op.drop_index('ix_approval_task_assignee', table_name='tab_approval_task')
    op.drop_table('tab_approval_task')
    op.drop_table('tab_approval_switch')
    op.drop_index(op.f('ix_tab_approval_node_flow_id'), table_name='tab_approval_node')
    op.drop_table('tab_approval_node')
    op.drop_index(op.f('ix_tab_approval_instance_flow_id'), table_name='tab_approval_instance')
    op.drop_index('ix_approval_instance_entity', table_name='tab_approval_instance')
    op.drop_table('tab_approval_instance')
    op.drop_index(op.f('ix_tab_approval_flow_entity'), table_name='tab_approval_flow')
    op.drop_table('tab_approval_flow')
    op.drop_index('ix_approval_action_instance', table_name='tab_approval_action')
    op.drop_table('tab_approval_action')
    # ### end Alembic commands ###
