"""survey_line_dates_source

Revision ID: 183ff05fcbc8
Revises: fac32d748eec
Create Date: 2026-07-03 03:19:41.784405
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183ff05fcbc8'
down_revision: Union[str, None] = 'fac32d748eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_survey_product_line', sa.Column('contact_date', sa.String(length=10), nullable=False))
    op.add_column('tab_survey_product_line', sa.Column('reply_date', sa.String(length=10), nullable=False))
    op.add_column('tab_survey_product_line', sa.Column('result_date', sa.String(length=10), nullable=False))
    op.add_column('tab_survey_supplier_line', sa.Column('source_of_information', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_survey_supplier_line', 'source_of_information')
    op.drop_column('tab_survey_product_line', 'result_date')
    op.drop_column('tab_survey_product_line', 'reply_date')
    op.drop_column('tab_survey_product_line', 'contact_date')
    # ### end Alembic commands ###
