"""noi rong cot icon help article

Revision ID: 1b5d0cb49327
Revises: a51129aee904
Create Date: 2026-08-05 01:41:38.540771
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b5d0cb49327'
down_revision: Union[str, None] = 'a51129aee904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_help_article', 'icon',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_help_article', 'icon',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
