"""tab_setting

Revision ID: 1c45703bbfd6
Revises: 183ff05fcbc8
Create Date: 2026-07-03 04:31:36.510919
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c45703bbfd6'
down_revision: Union[str, None] = '183ff05fcbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_setting',
    sa.Column('skey', sa.String(length=64), nullable=False),
    sa.Column('svalue', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_setting_skey'), 'tab_setting', ['skey'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_setting_skey'), table_name='tab_setting')
    op.drop_table('tab_setting')
    # ### end Alembic commands ###
