"""supplier fields + contract generic

Revision ID: 571ffb3c33ab
Revises: 216cddb1081a
Create Date: 2026-07-01 07:23:10.556555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '571ffb3c33ab'
down_revision: Union[str, None] = '216cddb1081a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_contract', sa.Column('party_type', sa.String(length=30), nullable=False))
    op.add_column('tab_contract', sa.Column('party_code', sa.String(length=50), nullable=False))
    op.add_column('tab_contract', sa.Column('party_name', sa.String(length=255), nullable=False))
    op.add_column('tab_contract', sa.Column('company_id', sa.BigInteger(), nullable=False))
    op.add_column('tab_contract', sa.Column('signed', sa.Boolean(), nullable=False))
    op.drop_index('ix_tab_contract_supplier_code', table_name='tab_contract')
    op.create_index(op.f('ix_tab_contract_party_code'), 'tab_contract', ['party_code'], unique=False)
    op.drop_column('tab_contract', 'filename')
    op.drop_column('tab_contract', 'supplier_code')
    op.drop_column('tab_contract', 'supplier_name')
    op.drop_column('tab_contract', 'payment_terms')
    op.drop_column('tab_contract', 'value')
    op.drop_column('tab_contract', 'file_url')
    op.drop_column('tab_employee', 'status')
    op.drop_column('tab_employee', 'role_name')
    op.add_column('tab_supplier', sa.Column('legal_type', sa.String(length=30), nullable=False))
    op.add_column('tab_supplier', sa.Column('contact_person', sa.String(length=100), nullable=False))
    op.add_column('tab_supplier', sa.Column('phone', sa.String(length=30), nullable=False))
    op.add_column('tab_supplier', sa.Column('bank_account', sa.String(length=50), nullable=False))
    op.add_column('tab_supplier', sa.Column('bank_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_supplier', 'bank_name')
    op.drop_column('tab_supplier', 'bank_account')
    op.drop_column('tab_supplier', 'phone')
    op.drop_column('tab_supplier', 'contact_person')
    op.drop_column('tab_supplier', 'legal_type')
    op.add_column('tab_employee', sa.Column('role_name', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=True))
    op.add_column('tab_employee', sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Chính thức'"), nullable=True))
    op.add_column('tab_contract', sa.Column('file_url', mysql.VARCHAR(length=1000), nullable=False))
    op.add_column('tab_contract', sa.Column('value', mysql.DECIMAL(precision=18, scale=2), nullable=False))
    op.add_column('tab_contract', sa.Column('payment_terms', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('tab_contract', sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('tab_contract', sa.Column('supplier_code', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('tab_contract', sa.Column('filename', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_tab_contract_party_code'), table_name='tab_contract')
    op.create_index('ix_tab_contract_supplier_code', 'tab_contract', ['supplier_code'], unique=False)
    op.drop_column('tab_contract', 'signed')
    op.drop_column('tab_contract', 'company_id')
    op.drop_column('tab_contract', 'party_name')
    op.drop_column('tab_contract', 'party_code')
    op.drop_column('tab_contract', 'party_type')
    # ### end Alembic commands ###
