"""user_scope add role_id

Revision ID: 6da57f7272f2
Revises: b9b6eb092ff8
Create Date: 2026-07-02 03:57:51.819583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da57f7272f2'
down_revision: Union[str, None] = 'b9b6eb092ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_user_scope', sa.Column('role_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_tab_user_scope_role_id'), 'tab_user_scope', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_user_scope_role_id'), table_name='tab_user_scope')
    op.drop_column('tab_user_scope', 'role_id')
    # ### end Alembic commands ###
