"""PR item required_date + line_status default

Revision ID: 88a2de6dda17
Revises: 6da57f7272f2
Create Date: 2026-07-02 09:09:37.208288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a2de6dda17'
down_revision: Union[str, None] = '6da57f7272f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_purchase_request_item', sa.Column('required_date', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_purchase_request_item', 'required_date')
    # ### end Alembic commands ###
