"""them bang comment

Revision ID: 9a9d26028071
Revises: f7de8fed036a
Create Date: 2026-07-18 04:38:02.434713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9d26028071'
down_revision: Union[str, None] = 'f7de8fed036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_comment',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('mention_user_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_comment_entity'), 'tab_comment', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_comment_entity_id'), 'tab_comment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tab_comment_parent_id'), 'tab_comment', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_comment_parent_id'), table_name='tab_comment')
    op.drop_index(op.f('ix_tab_comment_entity_id'), table_name='tab_comment')
    op.drop_index(op.f('ix_tab_comment_entity'), table_name='tab_comment')
    op.drop_table('tab_comment')
    # ### end Alembic commands ###
