"""them summary va icon cho help article

Revision ID: a51129aee904
Revises: 1c4f6cd23266
Create Date: 2026-08-05 01:29:45.388590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51129aee904'
down_revision: Union[str, None] = '1c4f6cd23266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_help_article', sa.Column('summary', sa.String(length=255), nullable=True))
    op.add_column('tab_help_article', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_help_article', 'icon')
    op.drop_column('tab_help_article', 'summary')
    # ### end Alembic commands ###
