"""add tab_user_scope

Revision ID: b9b6eb092ff8
Revises: fac1da01ec6e
Create Date: 2026-07-02 03:45:23.215572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b6eb092ff8'
down_revision: Union[str, None] = 'fac1da01ec6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_user_scope',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('dim', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_exclude', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_scope_entity'), 'tab_user_scope', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_user_scope_user_id'), 'tab_user_scope', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_user_scope_user_id'), table_name='tab_user_scope')
    op.drop_index(op.f('ix_tab_user_scope_entity'), table_name='tab_user_scope')
    op.drop_table('tab_user_scope')
    # ### end Alembic commands ###
