"""init schema

Revision ID: dafd7880380c
Revises: 
Create Date: 2026-07-01 04:36:46.866834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafd7880380c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_attachment',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_attachment_entity'), 'tab_attachment', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_attachment_entity_id'), 'tab_attachment', ['entity_id'], unique=False)
    op.create_table('tab_audit_log',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_audit_log_entity'), 'tab_audit_log', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_audit_log_entity_id'), 'tab_audit_log', ['entity_id'], unique=False)
    op.create_table('tab_brand',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_company',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=25), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('invoice_email', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_department',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_email_log',
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_employee',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_goods_receipt',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('po_code', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('qc_result', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_goods_receipt_delivery_id'), 'tab_goods_receipt', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_tab_goods_receipt_po_id'), 'tab_goods_receipt', ['po_id'], unique=False)
    op.create_table('tab_inventory',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_inventory_company_id'), 'tab_inventory', ['company_id'], unique=False)
    op.create_index(op.f('ix_tab_inventory_product_code'), 'tab_inventory', ['product_code'], unique=False)
    op.create_index(op.f('ix_tab_inventory_warehouse_code'), 'tab_inventory', ['warehouse_code'], unique=False)
    op.create_table('tab_inventory_move',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_inventory_move_company_id'), 'tab_inventory_move', ['company_id'], unique=False)
    op.create_index(op.f('ix_tab_inventory_move_product_code'), 'tab_inventory_move', ['product_code'], unique=False)
    op.create_index(op.f('ix_tab_inventory_move_warehouse_code'), 'tab_inventory_move', ['warehouse_code'], unique=False)
    op.create_table('tab_item_group',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('std_days', sa.String(length=20), nullable=False),
    sa.Column('std_days_unavail', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('apply_date', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tab_notification',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_notification_user_id'), 'tab_notification', ['user_id'], unique=False)
    op.create_table('tab_payable',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('po_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('incur_date', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remaining', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_payable_company_id'), 'tab_payable', ['company_id'], unique=False)
    op.create_index(op.f('ix_tab_payable_due_date'), 'tab_payable', ['due_date'], unique=False)
    op.create_index(op.f('ix_tab_payable_incur_date'), 'tab_payable', ['incur_date'], unique=False)
    op.create_index(op.f('ix_tab_payable_period'), 'tab_payable', ['period'], unique=False)
    op.create_index(op.f('ix_tab_payable_po_code'), 'tab_payable', ['po_code'], unique=False)
    op.create_index(op.f('ix_tab_payable_ref_id'), 'tab_payable', ['ref_id'], unique=False)
    op.create_index(op.f('ix_tab_payable_source_type'), 'tab_payable', ['source_type'], unique=False)
    op.create_index(op.f('ix_tab_payable_status'), 'tab_payable', ['status'], unique=False)
    op.create_index(op.f('ix_tab_payable_supplier_code'), 'tab_payable', ['supplier_code'], unique=False)
    op.create_table('tab_payment_request',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_payment_request_supplier_code'), 'tab_payment_request', ['supplier_code'], unique=False)
    op.create_table('tab_payment_request_line',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('payable_id', sa.BigInteger(), nullable=False),
    sa.Column('po_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_payment_request_line_request_id'), 'tab_payment_request_line', ['request_id'], unique=False)
    op.create_table('tab_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_print', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_permission_entity'), 'tab_permission', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_permission_role_id'), 'tab_permission', ['role_id'], unique=False)
    op.create_table('tab_po_delivery',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('po_item_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_no', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('carrier_code', sa.String(length=50), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=False),
    sa.Column('ship_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('ship_unit', sa.String(length=25), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('promised_date', sa.String(length=10), nullable=False),
    sa.Column('expected_date', sa.String(length=10), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('std_days', sa.BigInteger(), nullable=False),
    sa.Column('regulated_date', sa.String(length=10), nullable=False),
    sa.Column('diff_promise', sa.BigInteger(), nullable=False),
    sa.Column('diff_regulated', sa.BigInteger(), nullable=False),
    sa.Column('diff_required', sa.BigInteger(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('shipping_unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qc_result', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extra_request', sa.Text(), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_po_delivery_po_id'), 'tab_po_delivery', ['po_id'], unique=False)
    op.create_index(op.f('ix_tab_po_delivery_po_item_id'), 'tab_po_delivery', ['po_item_id'], unique=False)
    op.create_index(op.f('ix_tab_po_delivery_received_date'), 'tab_po_delivery', ['received_date'], unique=False)
    op.create_table('tab_po_item',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_name', sa.String(length=255), nullable=False),
    sa.Column('item_group', sa.String(length=100), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=False),
    sa.Column('fg_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_ready', sa.Boolean(), nullable=False),
    sa.Column('required_date', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('qty_request', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_order', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('line_status', sa.String(length=30), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_po_item_po_id'), 'tab_po_item', ['po_id'], unique=False)
    op.create_table('tab_product',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invoice_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('item_group', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_purchase_order',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('misa_code', sa.String(length=50), nullable=False),
    sa.Column('pr_code', sa.String(length=50), nullable=False),
    sa.Column('survey_code', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('nspt', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.String(length=10), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('payment_terms', sa.String(length=255), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('approve_note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tab_purchase_order_order_date'), 'tab_purchase_order', ['order_date'], unique=False)
    op.create_table('tab_purchase_request',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('requester_position', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('head_of_dept', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('request_date', sa.String(length=10), nullable=False),
    sa.Column('need_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('show_code_on_print', sa.Boolean(), nullable=False),
    sa.Column('suggested_supplier', sa.String(length=255), nullable=False),
    sa.Column('suggested_supplier_tax_code', sa.String(length=50), nullable=False),
    sa.Column('suggested_supplier_contact', sa.String(length=255), nullable=False),
    sa.Column('quote_filename', sa.String(length=255), nullable=False),
    sa.Column('quote_file_url', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_purchase_request_item',
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('item_group', sa.String(length=100), nullable=False),
    sa.Column('group_desc', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=False),
    sa.Column('line_status', sa.String(length=30), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_purchase_request_item_pr_id'), 'tab_purchase_request_item', ['pr_id'], unique=False)
    op.create_table('tab_report_snapshot',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_report_snapshot_key'), 'tab_report_snapshot', ['key'], unique=True)
    op.create_table('tab_role',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_supplier',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=25), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('supplier_type', sa.String(length=20), nullable=False),
    sa.Column('payment_terms', sa.String(length=255), nullable=False),
    sa.Column('vat', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_survey',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('survey_type', sa.String(length=10), nullable=False),
    sa.Column('pr_code', sa.String(length=50), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('result_due_date', sa.String(length=10), nullable=False),
    sa.Column('item_group', sa.String(length=100), nullable=False),
    sa.Column('requirement_detail', sa.Text(), nullable=False),
    sa.Column('request_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nspt', sa.String(length=100), nullable=False),
    sa.Column('approve_status', sa.String(length=20), nullable=False),
    sa.Column('approve_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_survey_product_line',
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('quote_unit', sa.String(length=25), nullable=False),
    sa.Column('moq', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('price_by_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('volume_range', sa.String(length=100), nullable=False),
    sa.Column('vat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('request_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('internal_unit', sa.String(length=25), nullable=False),
    sa.Column('amount_converted', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delivery_time', sa.String(length=100), nullable=False),
    sa.Column('delivery_place', sa.String(length=255), nullable=False),
    sa.Column('quote_file', sa.String(length=500), nullable=False),
    sa.Column('sample_ready', sa.Boolean(), nullable=False),
    sa.Column('sample_date', sa.String(length=10), nullable=False),
    sa.Column('sample_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('lab_result', sa.String(length=20), nullable=False),
    sa.Column('lab_note', sa.Text(), nullable=False),
    sa.Column('nspt_note', sa.String(length=20), nullable=False),
    sa.Column('nspt_reason', sa.Text(), nullable=False),
    sa.Column('line_approve', sa.String(length=20), nullable=False),
    sa.Column('line_approve_note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_survey_product_line_survey_id'), 'tab_survey_product_line', ['survey_id'], unique=False)
    op.create_table('tab_survey_supplier_line',
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_date', sa.String(length=10), nullable=False),
    sa.Column('reply_date', sa.String(length=10), nullable=False),
    sa.Column('result_date', sa.String(length=10), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=25), nullable=False),
    sa.Column('reg_address', sa.Text(), nullable=False),
    sa.Column('warehouse_address', sa.Text(), nullable=False),
    sa.Column('google_maps', sa.String(length=500), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('supply_group', sa.String(length=255), nullable=False),
    sa.Column('quote_folder', sa.String(length=500), nullable=False),
    sa.Column('production_tech', sa.String(length=255), nullable=False),
    sa.Column('production_time', sa.String(length=100), nullable=False),
    sa.Column('nvkd_eval', sa.String(length=100), nullable=False),
    sa.Column('invoice_policy', sa.String(length=255), nullable=False),
    sa.Column('reliability', sa.String(length=20), nullable=False),
    sa.Column('delivery_policy', sa.String(length=255), nullable=False),
    sa.Column('debt_policy', sa.String(length=50), nullable=False),
    sa.Column('defect_return', sa.String(length=255), nullable=False),
    sa.Column('nspt_note', sa.String(length=20), nullable=False),
    sa.Column('nspt_reason', sa.Text(), nullable=False),
    sa.Column('line_approve', sa.String(length=20), nullable=False),
    sa.Column('line_approve_note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_survey_supplier_line_survey_id'), 'tab_survey_supplier_line', ['survey_id'], unique=False)
    op.create_table('tab_unit',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_sub', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_email'), 'tab_user', ['email'], unique=False)
    op.create_index(op.f('ix_tab_user_employee_id'), 'tab_user', ['employee_id'], unique=False)
    op.create_table('tab_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_role_role_id'), 'tab_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_tab_user_role_user_id'), 'tab_user_role', ['user_id'], unique=False)
    op.create_table('tab_warehouse',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_warehouse')
    op.drop_index(op.f('ix_tab_user_role_user_id'), table_name='tab_user_role')
    op.drop_index(op.f('ix_tab_user_role_role_id'), table_name='tab_user_role')
    op.drop_table('tab_user_role')
    op.drop_index(op.f('ix_tab_user_employee_id'), table_name='tab_user')
    op.drop_index(op.f('ix_tab_user_email'), table_name='tab_user')
    op.drop_table('tab_user')
    op.drop_table('tab_unit')
    op.drop_index(op.f('ix_tab_survey_supplier_line_survey_id'), table_name='tab_survey_supplier_line')
    op.drop_table('tab_survey_supplier_line')
    op.drop_index(op.f('ix_tab_survey_product_line_survey_id'), table_name='tab_survey_product_line')
    op.drop_table('tab_survey_product_line')
    op.drop_table('tab_survey')
    op.drop_table('tab_supplier')
    op.drop_table('tab_role')
    op.drop_index(op.f('ix_tab_report_snapshot_key'), table_name='tab_report_snapshot')
    op.drop_table('tab_report_snapshot')
    op.drop_index(op.f('ix_tab_purchase_request_item_pr_id'), table_name='tab_purchase_request_item')
    op.drop_table('tab_purchase_request_item')
    op.drop_table('tab_purchase_request')
    op.drop_index(op.f('ix_tab_purchase_order_order_date'), table_name='tab_purchase_order')
    op.drop_table('tab_purchase_order')
    op.drop_table('tab_product')
    op.drop_index(op.f('ix_tab_po_item_po_id'), table_name='tab_po_item')
    op.drop_table('tab_po_item')
    op.drop_index(op.f('ix_tab_po_delivery_received_date'), table_name='tab_po_delivery')
    op.drop_index(op.f('ix_tab_po_delivery_po_item_id'), table_name='tab_po_delivery')
    op.drop_index(op.f('ix_tab_po_delivery_po_id'), table_name='tab_po_delivery')
    op.drop_table('tab_po_delivery')
    op.drop_index(op.f('ix_tab_permission_role_id'), table_name='tab_permission')
    op.drop_index(op.f('ix_tab_permission_entity'), table_name='tab_permission')
    op.drop_table('tab_permission')
    op.drop_index(op.f('ix_tab_payment_request_line_request_id'), table_name='tab_payment_request_line')
    op.drop_table('tab_payment_request_line')
    op.drop_index(op.f('ix_tab_payment_request_supplier_code'), table_name='tab_payment_request')
    op.drop_table('tab_payment_request')
    op.drop_index(op.f('ix_tab_payable_supplier_code'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_status'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_source_type'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_ref_id'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_po_code'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_period'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_incur_date'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_due_date'), table_name='tab_payable')
    op.drop_index(op.f('ix_tab_payable_company_id'), table_name='tab_payable')
    op.drop_table('tab_payable')
    op.drop_index(op.f('ix_tab_notification_user_id'), table_name='tab_notification')
    op.drop_table('tab_notification')
    op.drop_table('tab_item_group')
    op.drop_index(op.f('ix_tab_inventory_move_warehouse_code'), table_name='tab_inventory_move')
    op.drop_index(op.f('ix_tab_inventory_move_product_code'), table_name='tab_inventory_move')
    op.drop_index(op.f('ix_tab_inventory_move_company_id'), table_name='tab_inventory_move')
    op.drop_table('tab_inventory_move')
    op.drop_index(op.f('ix_tab_inventory_warehouse_code'), table_name='tab_inventory')
    op.drop_index(op.f('ix_tab_inventory_product_code'), table_name='tab_inventory')
    op.drop_index(op.f('ix_tab_inventory_company_id'), table_name='tab_inventory')
    op.drop_table('tab_inventory')
    op.drop_index(op.f('ix_tab_goods_receipt_po_id'), table_name='tab_goods_receipt')
    op.drop_index(op.f('ix_tab_goods_receipt_delivery_id'), table_name='tab_goods_receipt')
    op.drop_table('tab_goods_receipt')
    op.drop_table('tab_employee')
    op.drop_table('tab_email_log')
    op.drop_table('tab_department')
    op.drop_table('tab_company')
    op.drop_table('tab_brand')
    op.drop_index(op.f('ix_tab_audit_log_entity_id'), table_name='tab_audit_log')
    op.drop_index(op.f('ix_tab_audit_log_entity'), table_name='tab_audit_log')
    op.drop_table('tab_audit_log')
    op.drop_index(op.f('ix_tab_attachment_entity_id'), table_name='tab_attachment')
    op.drop_index(op.f('ix_tab_attachment_entity'), table_name='tab_attachment')
    op.drop_table('tab_attachment')
    # ### end Alembic commands ###
