"""them sort_order vao tab_file_link

Revision ID: f7de8fed036a
Revises: b3e1f7a2c9d4
Create Date: 2026-07-18 02:07:27.192166
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7de8fed036a'
down_revision: Union[str, None] = 'b3e1f7a2c9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_file_link', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_file_link', 'sort_order')
    # ### end Alembic commands ###
