"""add can_cancel to permission

Revision ID: fac1da01ec6e
Revises: 571ffb3c33ab
Create Date: 2026-07-02 03:03:33.765352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fac1da01ec6e'
down_revision: Union[str, None] = '571ffb3c33ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_employee', 'role_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('tab_employee', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Chính thức'"))
    op.add_column('tab_permission', sa.Column('can_cancel', sa.Boolean(), nullable=False))
    op.alter_column('tab_user', 'avatar',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_user', 'avatar',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_column('tab_permission', 'can_cancel')
    op.alter_column('tab_employee', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Chính thức'"))
    op.alter_column('tab_employee', 'role_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###
