"""survey_header_product_fields

Revision ID: fac32d748eec
Revises: 88a2de6dda17
Create Date: 2026-07-03 02:40:47.080120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac32d748eec'
down_revision: Union[str, None] = '88a2de6dda17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_survey', sa.Column('has_product_code', sa.Boolean(), nullable=False))
    op.add_column('tab_survey', sa.Column('item_code', sa.String(length=50), nullable=False))
    op.add_column('tab_survey', sa.Column('item_name', sa.String(length=255), nullable=False))
    op.add_column('tab_survey', sa.Column('uom', sa.String(length=25), nullable=False))
    op.add_column('tab_survey', sa.Column('proposed_rate', sa.Numeric(precision=18, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_survey', 'proposed_rate')
    op.drop_column('tab_survey', 'uom')
    op.drop_column('tab_survey', 'item_name')
    op.drop_column('tab_survey', 'item_code')
    op.drop_column('tab_survey', 'has_product_code')
    # ### end Alembic commands ###
